// This file is auto-generated by @hey-api/openapi-ts

/**
 * Current access log storage: null = main DB, else DataSource id. use_starrocks_audit for MySQL/StarRocks.
 */
export type AccessLogConfigPublic = {
    datasource_id?: (string | null);
    use_starrocks_audit?: boolean;
};

/**
 * Body for PUT /access-log-config.
 */
export type AccessLogConfigUpdate = {
    datasource_id?: (string | null);
    use_starrocks_audit?: boolean;
};

/**
 * Minimal DataSource info for access-log storage dropdown (no password).
 */
export type AccessLogDatasourceOption = {
    id: string;
    name: string;
    product_type: string;
};

/**
 * Response for GET /access-logs/datasource-options.
 */
export type AccessLogDatasourceOptionsOut = {
    data: Array<AccessLogDatasourceOption>;
};

/**
 * Response for GET /access-logs.
 */
export type AccessLogListOut = {
    data: Array<AccessRecordPublic>;
    total: number;
};

/**
 * Full access record for detail view (includes request_body, headers, params; human-readable api/client).
 */
export type AccessRecordDetail = {
    id: string;
    api_assignment_id: (string | null);
    app_client_id: (string | null);
    ip_address: string;
    http_method: string;
    path: string;
    status_code: number;
    request_body?: (string | null);
    request_headers?: (string | null);
    request_params?: (string | null);
    created_at: string;
    /**
     * Request duration in milliseconds
     */
    duration_ms?: (number | null);
    /**
     * e.g. GET /module/path or API name
     */
    api_display?: (string | null);
    /**
     * Client name
     */
    app_client_display?: (string | null);
};

/**
 * Schema for AccessRecord in list; optional body/headers/params preview (truncated).
 */
export type AccessRecordPublic = {
    id: string;
    api_assignment_id: (string | null);
    app_client_id: (string | null);
    ip_address: string;
    http_method: string;
    path: string;
    status_code: number;
    created_at: string;
    /**
     * Request duration in milliseconds
     */
    duration_ms?: (number | null);
    /**
     * Truncated for list
     */
    request_body?: (string | null);
    /**
     * Truncated for list
     */
    request_headers?: (string | null);
    /**
     * Truncated for list
     */
    request_params?: (string | null);
};

export type AlignmentFormat = {
    horizontal?: (string | null);
    vertical?: (string | null);
    wrap_text?: (boolean | null);
};

/**
 * API access type: public (no auth) or private (requires token).
 */
export type ApiAccessTypeEnum = 'public' | 'private';

/**
 * Body for POST /api-assignments/create.
 */
export type ApiAssignmentCreate = {
    module_id: string;
    name: string;
    path: string;
    http_method: HttpMethodEnum;
    execute_engine: ExecuteEngineEnum;
    datasource_id?: (string | null);
    description?: (string | null);
    /**
     * public: no auth required, private: requires token
     */
    access_type?: ApiAccessTypeEnum;
    /**
     * Max requests/min for this API. None = no limit.
     */
    rate_limit_per_minute?: (number | null);
    /**
     * Close DB connection after each request (e.g. StarRocks impersonation).
     */
    close_connection_after_execute?: boolean;
    sort_order?: number;
    /**
     * SQL/script → ApiContext (1-1)
     */
    content?: (string | null);
    /**
     * Optional Python script to transform executor result before returning
     */
    result_transform?: (string | null);
    /**
     * ApiGroup IDs to link
     */
    group_ids?: Array<(string)>;
    /**
     * Parameter definitions for validation
     */
    params?: Array<ApiParameter>;
    /**
     * Parameter validation scripts
     */
    param_validates?: Array<ApiParamValidate>;
};

/**
 * Body for POST /api-assignments/debug; Phase 2 returns 501.
 */
export type ApiAssignmentDebugIn = {
    id?: (string | null);
    content?: (string | null);
    execute_engine?: (ExecuteEngineEnum | null);
    datasource_id?: (string | null);
    /**
     * Optional params dict
     */
    params?: ({
    [key: string]: unknown;
} | null);
};

/**
 * Detail for GET /api-assignments/{id}; adds api_context and group_ids.
 */
export type ApiAssignmentDetail = {
    id: string;
    module_id: string;
    name: string;
    path: string;
    http_method: HttpMethodEnum;
    execute_engine: ExecuteEngineEnum;
    datasource_id: (string | null);
    description: (string | null);
    is_published: boolean;
    published_version_id: (string | null);
    access_type: ApiAccessTypeEnum;
    rate_limit_per_minute?: (number | null);
    close_connection_after_execute?: boolean;
    sort_order: number;
    created_at: string;
    updated_at: string;
    api_context?: (ApiContextPublic | null);
    group_ids?: Array<(string)>;
};

/**
 * Body for POST /api-assignments/list; pagination and optional filters.
 */
export type ApiAssignmentListIn = {
    /**
     * 1-based page number
     */
    page?: number;
    /**
     * Items per page
     */
    page_size?: number;
    module_id?: (string | null);
    is_published?: (boolean | null);
    name__ilike?: (string | null);
    http_method?: (HttpMethodEnum | null);
    execute_engine?: (ExecuteEngineEnum | null);
    access_type?: (ApiAccessTypeEnum | null);
    /**
     * Filter by exact list of IDs (for bulk fetch)
     */
    ids?: (Array<(string)> | null);
};

/**
 * Paginated list of ApiAssignment.
 */
export type ApiAssignmentListOut = {
    data: Array<ApiAssignmentPublic>;
    total: number;
};

/**
 * Response schema for ApiAssignment (core fields; omit api_context in list).
 */
export type ApiAssignmentPublic = {
    id: string;
    module_id: string;
    name: string;
    path: string;
    http_method: HttpMethodEnum;
    execute_engine: ExecuteEngineEnum;
    datasource_id: (string | null);
    description: (string | null);
    is_published: boolean;
    published_version_id: (string | null);
    access_type: ApiAccessTypeEnum;
    rate_limit_per_minute?: (number | null);
    close_connection_after_execute?: boolean;
    sort_order: number;
    created_at: string;
    updated_at: string;
};

/**
 * Body for POST /api-assignments/publish.
 */
export type ApiAssignmentPublishIn = {
    id: string;
    /**
     * Version to publish. Required for publish, optional for unpublish.
     */
    version_id?: (string | null);
};

/**
 * Body for POST /api-assignments/update; id required, others optional.
 */
export type ApiAssignmentUpdate = {
    id: string;
    module_id?: (string | null);
    name?: (string | null);
    path?: (string | null);
    http_method?: (HttpMethodEnum | null);
    execute_engine?: (ExecuteEngineEnum | null);
    datasource_id?: (string | null);
    description?: (string | null);
    access_type?: (ApiAccessTypeEnum | null);
    /**
     * Max requests/min for this API. None = no limit.
     */
    rate_limit_per_minute?: (number | null);
    close_connection_after_execute?: (boolean | null);
    sort_order?: (number | null);
    content?: (string | null);
    result_transform?: (string | null);
    /**
     * If set, replace group links
     */
    group_ids?: (Array<(string)> | null);
    /**
     * If set, replace parameter definitions
     */
    params?: (Array<ApiParameter> | null);
    /**
     * If set, replace parameter validation scripts
     */
    param_validates?: (Array<ApiParamValidate> | null);
};

/**
 * Response schema for ApiContext (included in ApiAssignmentDetail).
 */
export type ApiContextPublic = {
    id: string;
    api_assignment_id: string;
    content: string;
    /**
     * Parameter definitions: list of {name, location, data_type, is_required, default_value, description}
     */
    params?: (Array<{
    [key: string]: unknown;
}> | null);
    /**
     * Parameter validation scripts: list of {name, validation_script, message_when_fail}
     */
    param_validates?: (Array<{
    [key: string]: unknown;
}> | null);
    /**
     * Python script to transform executor result before returning
     */
    result_transform?: (string | null);
    created_at: string;
    updated_at: string;
};

/**
 * Body for POST /groups/create.
 */
export type ApiGroupCreate = {
    name: string;
    description?: (string | null);
    is_active?: boolean;
};

/**
 * Detail response for GET /groups/{id}; includes api_assignment_ids.
 */
export type ApiGroupDetail = {
    id: string;
    name: string;
    description: (string | null);
    is_active: boolean;
    created_at: string;
    updated_at: string;
    api_assignment_ids?: Array<(string)>;
};

/**
 * Body for POST /groups/list; pagination and optional filters.
 */
export type ApiGroupListIn = {
    /**
     * 1-based page number
     */
    page?: number;
    /**
     * Items per page
     */
    page_size?: number;
    name__ilike?: (string | null);
    is_active?: (boolean | null);
};

/**
 * Paginated list of ApiGroup.
 */
export type ApiGroupListOut = {
    data: Array<ApiGroupPublic>;
    total: number;
};

/**
 * Response schema for ApiGroup.
 */
export type ApiGroupPublic = {
    id: string;
    name: string;
    description: (string | null);
    is_active: boolean;
    created_at: string;
    updated_at: string;
};

/**
 * Body for POST /groups/update; id required, others optional.
 */
export type ApiGroupUpdate = {
    id: string;
    name?: (string | null);
    description?: (string | null);
    is_active?: (boolean | null);
};

/**
 * Body for POST /macro-defs/create.
 */
export type ApiMacroDefCreate = {
    /**
     * Null = global macro_def
     */
    module_id?: (string | null);
    name: string;
    macro_type: MacroTypeEnum;
    content: string;
    description?: (string | null);
    sort_order?: number;
};

/**
 * Detail for GET /macro-defs/{id}; adds used_by_apis_count.
 */
export type ApiMacroDefDetail = {
    id: string;
    module_id: (string | null);
    name: string;
    macro_type: MacroTypeEnum;
    content: string;
    description: (string | null);
    sort_order: number;
    is_published?: boolean;
    published_version_id?: (string | null);
    created_at: string;
    updated_at: string;
    /**
     * Number of APIs in scope that use this macro_def
     */
    used_by_apis_count?: number;
};

/**
 * Body for POST /macro-defs/list; pagination and optional filters.
 */
export type ApiMacroDefListIn = {
    /**
     * 1-based page number
     */
    page?: number;
    /**
     * Items per page
     */
    page_size?: number;
    /**
     * Filter by module; null = global only
     */
    module_id?: (string | null);
    macro_type?: (MacroTypeEnum | null);
    name__ilike?: (string | null);
};

/**
 * Paginated list of ApiMacroDef.
 */
export type ApiMacroDefListOut = {
    data: Array<ApiMacroDefPublic>;
    total: number;
};

/**
 * Response schema for ApiMacroDef.
 */
export type ApiMacroDefPublic = {
    id: string;
    module_id: (string | null);
    name: string;
    macro_type: MacroTypeEnum;
    content: string;
    description: (string | null);
    sort_order: number;
    is_published?: boolean;
    published_version_id?: (string | null);
    created_at: string;
    updated_at: string;
};

/**
 * Body for POST /macro-defs/publish.
 */
export type ApiMacroDefPublishIn = {
    id: string;
    /**
     * Required for publish.
     */
    version_id?: (string | null);
};

/**
 * Body for POST /macro-defs/update; id required, others optional.
 */
export type ApiMacroDefUpdate = {
    id: string;
    module_id?: (string | null);
    name?: (string | null);
    macro_type?: (MacroTypeEnum | null);
    content?: (string | null);
    description?: (string | null);
    sort_order?: (number | null);
};

/**
 * Body for POST /modules/create.
 */
export type ApiModuleCreate = {
    name: string;
    description?: (string | null);
    sort_order?: number;
    is_active?: boolean;
};

/**
 * Body for POST /modules/list; pagination and optional filters.
 */
export type ApiModuleListIn = {
    /**
     * 1-based page number
     */
    page?: number;
    /**
     * Items per page
     */
    page_size?: number;
    name__ilike?: (string | null);
    is_active?: (boolean | null);
};

/**
 * Paginated list of ApiModule.
 */
export type ApiModuleListOut = {
    data: Array<ApiModulePublic>;
    total: number;
};

/**
 * Response schema for ApiModule.
 */
export type ApiModulePublic = {
    id: string;
    name: string;
    description: (string | null);
    sort_order: number;
    is_active: boolean;
    created_at: string;
    updated_at: string;
};

/**
 * Body for POST /modules/update; id required, others optional.
 */
export type ApiModuleUpdate = {
    id: string;
    name?: (string | null);
    description?: (string | null);
    sort_order?: (number | null);
    is_active?: (boolean | null);
};

/**
 * Parameter definition for API validation.
 */
export type ApiParameter = {
    /**
     * Parameter name
     */
    name: string;
    /**
     * Parameter location: query, header, or body
     */
    location: string;
    /**
     * Data type: string, number, integer, boolean, array, object, etc.
     */
    data_type?: (string | null);
    /**
     * Whether this parameter is required (cannot be null/empty)
     */
    is_required?: boolean;
    /**
     * Validation type: 'regex' or 'python'
     */
    validate_type?: (string | null);
    /**
     * Validation: regex pattern (if validate_type='regex') or Python function code (if validate_type='python')
     */
    validate?: (string | null);
    /**
     * Error message shown when validation fails
     */
    validate_message?: (string | null);
    /**
     * Default value for this parameter (used in debug UI and as fallback)
     */
    default_value?: (string | null);
    /**
     * Human-readable description of the parameter (meaning, usage)
     */
    description?: (string | null);
};

/**
 * Parameter validation script definition.
 */
export type ApiParamValidate = {
    /**
     * Parameter name to validate
     */
    name: string;
    /**
     * Python validation script (e.g., 'def validate(value): return True')
     */
    validation_script?: (string | null);
    /**
     * Error message shown when validation fails
     */
    message_when_fail?: (string | null);
};

/**
 * Body for POST /clients/create.
 *
 * By default, the backend generates ``client_id`` and hashes ``client_secret``.
 * For advanced scenarios, a custom ``client_id`` and/or ``client_secret`` can
 * be provided explicitly from the caller.
 */
export type AppClientCreate = {
    name: string;
    /**
     * Optional custom client_id; if omitted, backend generates one.
     */
    client_id?: (string | null);
    /**
     * Plain secret; stored hashed. Frontend may auto-generate if omitted in UI.
     */
    client_secret: string;
    description?: (string | null);
    /**
     * Max requests/min for this client. None = no limit.
     */
    rate_limit_per_minute?: (number | null);
    /**
     * Max concurrent requests in flight for this client. None = use global default.
     */
    max_concurrent?: (number | null);
    /**
     * JWT token lifetime in seconds. None = use global default (3600s).
     */
    token_expire_seconds?: (number | null);
    is_active?: boolean;
    /**
     * ApiGroups to allow API access; stored in app_client_group_link
     */
    group_ids?: (Array<(string)> | null);
    /**
     * Direct APIs (outside groups) the client can call; stored in app_client_api_link
     */
    api_assignment_ids?: (Array<(string)> | null);
    /**
     * Report modules the client can generate reports for; stored in report_module_client_link
     */
    report_module_ids?: (Array<(string)> | null);
};

/**
 * Detail response for GET /clients/{id}; includes group_ids, api_assignment_ids, and effective_api_assignment_ids.
 */
export type AppClientDetail = {
    id: string;
    name: string;
    client_id: string;
    description: (string | null);
    rate_limit_per_minute?: (number | null);
    max_concurrent?: (number | null);
    token_expire_seconds?: (number | null);
    is_active: boolean;
    created_at: string;
    updated_at: string;
    group_ids?: Array<(string)>;
    api_assignment_ids?: Array<(string)>;
    report_module_ids?: Array<(string)>;
    /**
     * Union of direct api_assignment_ids + APIs reachable via assigned groups (ApiAssignmentGroupLink). This is the actual set of APIs the client can call, matching gateway auth logic.
     */
    effective_api_assignment_ids?: Array<(string)>;
};

/**
 * Body for POST /clients/list; pagination and optional filters.
 */
export type AppClientListIn = {
    /**
     * 1-based page number
     */
    page?: number;
    /**
     * Items per page
     */
    page_size?: number;
    name__ilike?: (string | null);
    is_active?: (boolean | null);
};

/**
 * Paginated list of AppClient.
 */
export type AppClientListOut = {
    data: Array<AppClientPublic>;
    total: number;
};

/**
 * Response schema; excludes client_secret (see regenerate-secret for one-time plain secret).
 */
export type AppClientPublic = {
    id: string;
    name: string;
    client_id: string;
    description: (string | null);
    rate_limit_per_minute?: (number | null);
    max_concurrent?: (number | null);
    token_expire_seconds?: (number | null);
    is_active: boolean;
    created_at: string;
    updated_at: string;
};

/**
 * Response for POST /clients/{id}/regenerate-secret; plain secret shown once.
 */
export type AppClientRegenerateSecretOut = {
    message?: string;
    client_secret: string;
};

/**
 * Body for POST /clients/update; id required. client_id and client_secret not updated here.
 */
export type AppClientUpdate = {
    id: string;
    name?: (string | null);
    description?: (string | null);
    /**
     * Max requests/min for this client. None = no limit.
     */
    rate_limit_per_minute?: (number | null);
    /**
     * Max concurrent requests in flight for this client. None = use global default.
     */
    max_concurrent?: (number | null);
    /**
     * JWT token lifetime in seconds. None = use global default (3600s).
     */
    token_expire_seconds?: (number | null);
    is_active?: (boolean | null);
    group_ids?: (Array<(string)> | null);
    api_assignment_ids?: (Array<(string)> | null);
    report_module_ids?: (Array<(string)> | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type BorderFormat = {
    style?: (string | null);
    color?: (string | null);
};

export type CellFormat = {
    font?: (FontFormat | null);
    fill?: (FillFormat | null);
    border?: (BorderFormat | null);
    alignment?: (AlignmentFormat | null);
    number_format?: (string | null);
};

export type ClientIdsOut = {
    client_ids: Array<(string)>;
};

export type ClientIdsUpdate = {
    client_ids: Array<(string)>;
};

/**
 * Body for POST /datasources/create.
 */
export type DataSourceCreate = {
    name: string;
    product_type: ProductTypeEnum;
    host: string;
    port?: number;
    database: string;
    username: string;
    /**
     * Optional; leave empty for no password.
     */
    password?: string;
    driver_version?: (string | null);
    description?: (string | null);
    is_active?: boolean;
    /**
     * If True, close DB connection after each request (e.g. for StarRocks impersonation).
     */
    close_connection_after_execute?: boolean;
    /**
     * For Trino: use HTTPS. When True, password is required.
     */
    use_ssl?: boolean;
};

/**
 * Body for POST /datasources/list; pagination and optional filters.
 */
export type DataSourceListIn = {
    /**
     * 1-based page number
     */
    page?: number;
    /**
     * Items per page
     */
    page_size?: number;
    product_type?: (ProductTypeEnum | null);
    is_active?: (boolean | null);
    name__ilike?: (string | null);
};

/**
 * Paginated list of datasources.
 */
export type DataSourceListOut = {
    data: Array<DataSourcePublic>;
    total: number;
};

/**
 * Body for POST /datasources/preTest; connection params only.
 */
export type DataSourcePreTestIn = {
    product_type: ProductTypeEnum;
    host: string;
    port?: number;
    database: string;
    username: string;
    /**
     * Optional.
     */
    password?: (string | null);
    /**
     * For Trino: use HTTPS. When True, password required.
     */
    use_ssl?: boolean;
};

/**
 * Response schema; password omitted for security.
 */
export type DataSourcePublic = {
    id: string;
    name: string;
    product_type: ProductTypeEnum;
    host: string;
    port: number;
    database: string;
    username: string;
    driver_version: (string | null);
    description: (string | null);
    is_active: boolean;
    close_connection_after_execute: boolean;
    use_ssl: boolean;
    created_at: string;
    updated_at: string;
};

/**
 * Response for /datasources/test/{id} and /datasources/preTest.
 */
export type DataSourceTestResult = {
    ok: boolean;
    message: string;
};

/**
 * Body for POST /datasources/update; id required, others optional.
 */
export type DataSourceUpdate = {
    id: string;
    name?: (string | null);
    product_type?: (ProductTypeEnum | null);
    host?: (string | null);
    port?: (number | null);
    database?: (string | null);
    username?: (string | null);
    password?: (string | null);
    driver_version?: (string | null);
    description?: (string | null);
    is_active?: (boolean | null);
    close_connection_after_execute?: (boolean | null);
    use_ssl?: (boolean | null);
};

/**
 * Execution engine: SQL (Jinja2) or SCRIPT (Python).
 */
export type ExecuteEngineEnum = 'SQL' | 'SCRIPT';

export type ExecutionStatusEnum = 'pending' | 'running' | 'success' | 'failed';

export type FillFormat = {
    bg_color?: (string | null);
    pattern?: (string | null);
};

export type FontFormat = {
    name?: (string | null);
    size?: (number | null);
    bold?: (boolean | null);
    italic?: (boolean | null);
    color?: (string | null);
};

export type FormatConfig = {
    header?: (CellFormat | null);
    data?: (CellFormat | null);
    column_widths?: ({
    [key: string]: (number);
} | null);
    auto_fit?: (boolean | null);
    auto_fit_max_width?: (number | null);
    wrap_text?: (boolean | null);
};

/**
 * Response for GET /api/token/generate (legacy migration: expireAt unix + token).
 */
export type GatewayTokenGenerateGetResponse = {
    /**
     * Unix timestamp when token expires
     */
    expireAt: number;
    token: string;
};

/**
 * Response for POST /api/token/generate.
 */
export type GatewayTokenResponse = {
    access_token: string;
    token_type?: string;
    expires_in: number;
};

/**
 * HTTP methods for API assignments.
 */
export type HttpMethodEnum = 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Body for POST /macro-defs/{id}/versions/create.
 */
export type MacroDefVersionCommitCreate = {
    commit_message?: (string | null);
};

/**
 * Full schema for MacroDefVersionCommit including content_snapshot.
 */
export type MacroDefVersionCommitDetail = {
    id: string;
    api_macro_def_id: string;
    version: number;
    content_snapshot: string;
    commit_message: (string | null);
    committed_by_id: (string | null);
    committed_by_email?: (string | null);
    committed_by_username?: (string | null);
    committed_at: string;
};

/**
 * Response for GET /macro-defs/{id}/versions.
 */
export type MacroDefVersionCommitListOut = {
    data: Array<MacroDefVersionCommitPublic>;
};

/**
 * Minimal schema for MacroDefVersionCommit in list.
 */
export type MacroDefVersionCommitPublic = {
    id: string;
    api_macro_def_id: string;
    version: number;
    commit_message: (string | null);
    committed_by_id: (string | null);
    committed_by_email?: (string | null);
    committed_by_username?: (string | null);
    committed_at: string;
};

/**
 * Macro type: Jinja2 for SQL templates, Python for script engine.
 */
export type MacroTypeEnum = 'JINJA' | 'PYTHON';

export type MappingPreviewOut = {
    mapping_id: string;
    sheet_name: string;
    start_cell: string;
    columns: Array<(string)>;
    rows: Array<{
        [key: string]: unknown;
    }>;
    error?: (string | null);
};

export type Message = {
    message: string;
};

/**
 * HTTP method breakdown for GET /overview/status-breakdown.
 */
export type MethodBreakdownPoint = {
    method: string;
    count: number;
};

/**
 * Response for GET /users/me/permissions.
 */
export type MyPermissionsOut = {
    data: Array<PermissionItem>;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Response for GET /overview/stats; counts of main entities.
 */
export type OverviewStats = {
    datasources?: number;
    modules?: number;
    groups?: number;
    apis_total?: number;
    apis_published?: number;
    clients?: number;
};

/**
 * Single permission entry for GET /me/permissions.
 */
export type PermissionItem = {
    resource_type: string;
    action: string;
    resource_id?: (string | null);
};

/**
 * Response for GET /permissions/list.
 */
export type PermissionListOut = {
    data: Array<PermissionPublic>;
};

/**
 * Permission in list response.
 */
export type PermissionPublic = {
    id: string;
    resource_type: string;
    action: string;
    resource_id?: (string | null);
};

/**
 * Supported database product types (postgres, mysql, trino).
 */
export type ProductTypeEnum = 'postgres' | 'mysql' | 'trino' | 'minio';

/**
 * Response for GET /overview/recent-access.
 */
export type RecentAccessOut = {
    data: Array<AccessRecordPublic>;
};

/**
 * Response for GET /overview/recent-commits.
 */
export type RecentCommitsOut = {
    data: Array<VersionCommitPublic>;
};

export type ReportExecutionListOut = {
    data: Array<ReportExecutionPublic>;
    total: number;
};

export type ReportExecutionPublic = {
    id: string;
    report_template_id: string;
    status: ExecutionStatusEnum;
    parameters: ({
    [key: string]: unknown;
} | null);
    output_minio_path: (string | null);
    output_url: (string | null);
    error_message: (string | null);
    processed_rows?: number;
    progress_pct?: (number | null);
    started_at: (string | null);
    completed_at: (string | null);
    created_at: string;
};

export type ReportGenerateIn = {
    parameters?: ({
    [key: string]: unknown;
} | null);
    async?: boolean;
};

export type ReportGenerateOut = {
    execution_id: string;
    status: ExecutionStatusEnum;
    output_url?: (string | null);
    output_minio_path?: (string | null);
};

export type ReportModuleCreate = {
    name: string;
    description?: (string | null);
    minio_datasource_id: string;
    sql_datasource_id: string;
    default_template_bucket: string;
    default_output_bucket: string;
};

export type ReportModuleDetail = {
    id: string;
    name: string;
    description: (string | null);
    minio_datasource_id: string;
    sql_datasource_id: string;
    default_template_bucket: string;
    default_output_bucket: string;
    is_active: boolean;
    created_at: string;
    updated_at: string;
    templates?: Array<ReportTemplatePublic>;
    client_ids?: Array<(string)>;
};

export type ReportModuleListIn = {
    page?: number;
    page_size?: number;
    name__ilike?: (string | null);
    is_active?: (boolean | null);
};

export type ReportModuleListOut = {
    data: Array<ReportModulePublic>;
    total: number;
};

export type ReportModulePublic = {
    id: string;
    name: string;
    description: (string | null);
    minio_datasource_id: string;
    sql_datasource_id: string;
    default_template_bucket: string;
    default_output_bucket: string;
    is_active: boolean;
    created_at: string;
    updated_at: string;
};

export type ReportModuleUpdate = {
    id: string;
    name?: (string | null);
    description?: (string | null);
    minio_datasource_id?: (string | null);
    sql_datasource_id?: (string | null);
    default_template_bucket?: (string | null);
    default_output_bucket?: (string | null);
    is_active?: (boolean | null);
};

export type ReportPreviewIn = {
    parameters?: ({
    [key: string]: unknown;
} | null);
    row_limit?: number;
};

export type ReportPreviewOut = {
    mappings: Array<MappingPreviewOut>;
};

export type ReportTemplateCreate = {
    name: string;
    description?: (string | null);
    template_bucket?: string;
    template_path?: string;
    output_bucket: string;
    output_prefix?: string;
    recalc_enabled?: boolean;
    recalc_timeout_override?: (number | null);
    output_sheet?: (string | null);
    format_config?: (FormatConfig | null);
    sheet_mappings?: (Array<SheetMappingCreate> | null);
};

export type ReportTemplateDetail = {
    id: string;
    report_module_id: string;
    name: string;
    description: (string | null);
    template_bucket: string;
    template_path: string;
    output_bucket: string;
    output_prefix: string;
    recalc_enabled: boolean;
    recalc_timeout_override?: (number | null);
    output_sheet: (string | null);
    format_config: ({
    [key: string]: unknown;
} | null);
    is_active: boolean;
    created_at: string;
    updated_at: string;
    sheet_mappings?: Array<SheetMappingPublic>;
    client_ids?: Array<(string)>;
};

export type ReportTemplateListIn = {
    page?: number;
    page_size?: number;
    name__ilike?: (string | null);
    module_id?: (string | null);
    is_active?: (boolean | null);
};

export type ReportTemplateListOut = {
    data: Array<ReportTemplatePublic>;
    total: number;
};

export type ReportTemplatePublic = {
    id: string;
    report_module_id: string;
    name: string;
    description: (string | null);
    template_bucket: string;
    template_path: string;
    output_bucket: string;
    output_prefix: string;
    recalc_enabled: boolean;
    recalc_timeout_override?: (number | null);
    output_sheet: (string | null);
    format_config: ({
    [key: string]: unknown;
} | null);
    is_active: boolean;
    created_at: string;
    updated_at: string;
};

export type ReportTemplateUpdate = {
    id: string;
    name?: (string | null);
    description?: (string | null);
    template_bucket?: (string | null);
    template_path?: (string | null);
    output_bucket?: (string | null);
    output_prefix?: (string | null);
    recalc_enabled?: (boolean | null);
    recalc_timeout_override?: (number | null);
    output_sheet?: (string | null);
    format_config?: (FormatConfig | null);
    is_active?: (boolean | null);
};

/**
 * Response for GET /overview/requests-by-day.
 */
export type RequestsByDayOut = {
    data: Array<RequestsByDayPoint>;
};

/**
 * Point for GET /overview/requests-by-day.
 */
export type RequestsByDayPoint = {
    day: string;
    count: number;
};

export type ResourceName = {
    id: string;
    name: string;
};

/**
 * Response for GET /permissions/resource-names.
 */
export type ResourceNamesOut = {
    datasources: Array<ResourceName>;
    modules: Array<ResourceName>;
    api_assignments: Array<ResourceName>;
    groups: Array<ResourceName>;
    macro_defs: Array<ResourceName>;
    clients: Array<ResourceName>;
};

/**
 * Body for POST /roles. Create custom role.
 */
export type RoleCreateIn = {
    name: string;
    description?: (string | null);
    permission_ids?: Array<(string)>;
};

/**
 * Response for GET /roles/{id}.
 */
export type RoleDetailOut = {
    id: string;
    name: string;
    description?: (string | null);
    permission_ids?: Array<(string)>;
    user_count?: number;
};

/**
 * Response for GET /roles/list.
 */
export type RoleListOut = {
    data: Array<RolePublic>;
};

/**
 * Role in list response (with optional user_count for list view).
 */
export type RolePublic = {
    id: string;
    name: string;
    description?: (string | null);
    user_count?: number;
};

/**
 * Body for PUT /roles/{id}. All optional; permission_ids replaces role's permissions.
 */
export type RoleUpdateIn = {
    name?: (string | null);
    description?: (string | null);
    permission_ids?: (Array<(string)> | null);
};

/**
 * Response for GET /roles/{id}/users.
 */
export type RoleUsersOut = {
    data: Array<UserPublic>;
};

export type SheetMappingBatchUpdate = {
    mappings: Array<SheetMappingUpdate>;
};

export type SheetMappingCreate = {
    sort_order?: number;
    sheet_name: string;
    start_cell: string;
    write_mode?: SheetWriteModeEnum;
    write_headers?: boolean;
    gap_rows?: number;
    format_config?: (FormatConfig | null);
    sql_content: string;
    description?: (string | null);
};

export type SheetMappingPublic = {
    id: string;
    report_template_id: string;
    sort_order: number;
    sheet_name: string;
    start_cell: string;
    write_mode: SheetWriteModeEnum;
    write_headers: boolean;
    gap_rows: number;
    format_config: ({
    [key: string]: unknown;
} | null);
    sql_content: string;
    description: (string | null);
    is_active: boolean;
    created_at: string;
    updated_at: string;
};

export type SheetMappingUpdate = {
    id: string;
    sort_order?: (number | null);
    sheet_name?: (string | null);
    start_cell?: (string | null);
    write_mode?: (SheetWriteModeEnum | null);
    write_headers?: (boolean | null);
    gap_rows?: (number | null);
    format_config?: (FormatConfig | null);
    sql_content?: (string | null);
    description?: (string | null);
    is_active?: (boolean | null);
};

export type SheetWriteModeEnum = 'rows' | 'single';

/**
 * Response for GET /overview/status-breakdown.
 */
export type StatusBreakdownOut = {
    by_status: Array<StatusBreakdownPoint>;
    by_method: Array<MethodBreakdownPoint>;
    total: number;
    avg_duration_ms: (number | null);
};

/**
 * Status category breakdown for GET /overview/status-breakdown.
 */
export type StatusBreakdownPoint = {
    category: string;
    count: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * Point for GET /overview/top-paths.
 */
export type TopPathPoint = {
    path: string;
    http_method: string;
    count: number;
    avg_duration_ms?: (number | null);
    success_count?: number;
    fail_count?: number;
};

/**
 * Response for GET /overview/top-paths.
 */
export type TopPathsOut = {
    data: Array<TopPathPoint>;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    username: string;
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    username: string;
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    username: string;
    email?: (string | null);
    password: string;
    full_name?: (string | null);
};

/**
 * Response for GET/PUT /users/{user_id}/roles.
 */
export type UserRolesOut = {
    user_id: string;
    role_ids: Array<(string)>;
};

/**
 * Body for PUT /users/{user_id}/roles. Replaces user's roles.
 */
export type UserRolesUpdateIn = {
    role_ids?: Array<(string)>;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    username?: (string | null);
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    username?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

/**
 * Body for POST /api-assignments/{id}/versions/create.
 */
export type VersionCommitCreate = {
    commit_message?: (string | null);
};

/**
 * Full schema for VersionCommit including content_snapshot.
 */
export type VersionCommitDetail = {
    id: string;
    api_assignment_id: string;
    version: number;
    content_snapshot: string;
    /**
     * Snapshot of parameter definitions at commit time
     */
    params_snapshot?: (Array<{
    [key: string]: unknown;
}> | null);
    /**
     * Snapshot of parameter validation scripts at commit time
     */
    param_validates_snapshot?: (Array<{
    [key: string]: unknown;
}> | null);
    /**
     * Snapshot of Python result transform script at commit time
     */
    result_transform_snapshot?: (string | null);
    commit_message: (string | null);
    committed_by_id: (string | null);
    /**
     * Email of user who created this version
     */
    committed_by_email?: (string | null);
    /**
     * Username of user who created this version
     */
    committed_by_username?: (string | null);
    committed_at: string;
};

/**
 * Response for GET /api-assignments/{id}/versions.
 */
export type VersionCommitListOut = {
    data: Array<VersionCommitPublic>;
};

/**
 * Minimal schema for VersionCommit in recent-commits; content_snapshot excluded.
 */
export type VersionCommitPublic = {
    id: string;
    api_assignment_id: string;
    version: number;
    commit_message: (string | null);
    committed_by_id: (string | null);
    /**
     * Email of user who created this version
     */
    committed_by_email?: (string | null);
    /**
     * Username of user who created this version
     */
    committed_by_username?: (string | null);
    /**
     * HTTP method of the API (GET, POST, etc.)
     */
    http_method?: (string | null);
    /**
     * Full API path pattern: /{module}/{path}
     */
    full_path?: (string | null);
    committed_at: string;
};

export type AccessLogsGetAccessLogDatasourceOptionsResponse = (AccessLogDatasourceOptionsOut);

export type AccessLogsGetAccessLogConfigResponse = (AccessLogConfigPublic);

export type AccessLogsUpdateAccessLogConfigData = {
    requestBody: AccessLogConfigUpdate;
};

export type AccessLogsUpdateAccessLogConfigResponse = (AccessLogConfigPublic);

export type AccessLogsListAccessLogsData = {
    /**
     * Filter by API assignment UUID
     */
    apiAssignmentId?: (string | null);
    /**
     * Filter by app client UUID
     */
    appClientId?: (string | null);
    /**
     * Filter by group UUID (resolves to API assignment ids)
     */
    groupId?: (string | null);
    /**
     * Filter by HTTP method (GET, POST, ...)
     */
    httpMethod?: (string | null);
    /**
     * Filter by client IP
     */
    ipAddress?: (string | null);
    /**
     * Filter by module UUID (resolves to API assignment ids)
     */
    moduleId?: (string | null);
    page?: number;
    pageSize?: number;
    /**
     * Filter by path (substring)
     */
    pathIlike?: (string | null);
    /**
     * all | success | fail
     */
    status?: (string | null);
    /**
     * From (inclusive)
     */
    timeFrom?: (string | null);
    /**
     * To (inclusive)
     */
    timeTo?: (string | null);
};

export type AccessLogsListAccessLogsResponse = (AccessLogListOut);

export type AccessLogsGetAccessLogDetailData = {
    logId: string;
};

export type AccessLogsGetAccessLogDetailResponse = (AccessRecordDetail);

export type AccessLogsInitExternalAccessLogTableResponse = (Message);

export type ApiAssignmentsListApiAssignmentsData = {
    requestBody: ApiAssignmentListIn;
};

export type ApiAssignmentsListApiAssignmentsResponse = (ApiAssignmentListOut);

export type ApiAssignmentsCreateApiAssignmentData = {
    requestBody: ApiAssignmentCreate;
};

export type ApiAssignmentsCreateApiAssignmentResponse = (ApiAssignmentPublic);

export type ApiAssignmentsUpdateApiAssignmentData = {
    requestBody: ApiAssignmentUpdate;
};

export type ApiAssignmentsUpdateApiAssignmentResponse = (ApiAssignmentPublic);

export type ApiAssignmentsPublishApiAssignmentData = {
    requestBody: ApiAssignmentPublishIn;
};

export type ApiAssignmentsPublishApiAssignmentResponse = (ApiAssignmentPublic);

export type ApiAssignmentsUnpublishApiAssignmentData = {
    requestBody: ApiAssignmentPublishIn;
};

export type ApiAssignmentsUnpublishApiAssignmentResponse = (ApiAssignmentPublic);

export type ApiAssignmentsDebugApiAssignmentData = {
    requestBody: ApiAssignmentDebugIn;
};

export type ApiAssignmentsDebugApiAssignmentResponse = (unknown);

export type ApiAssignmentsDeleteApiAssignmentData = {
    id: string;
};

export type ApiAssignmentsDeleteApiAssignmentResponse = (Message);

export type ApiAssignmentsGetApiAssignmentData = {
    id: string;
};

export type ApiAssignmentsGetApiAssignmentResponse = (ApiAssignmentDetail);

export type ApiAssignmentsCreateVersionData = {
    id: string;
    requestBody: VersionCommitCreate;
};

export type ApiAssignmentsCreateVersionResponse = (VersionCommitDetail);

export type ApiAssignmentsListVersionsData = {
    id: string;
    limit?: number;
    skip?: number;
};

export type ApiAssignmentsListVersionsResponse = (VersionCommitListOut);

export type ApiAssignmentsGetVersionData = {
    versionId: string;
};

export type ApiAssignmentsGetVersionResponse = (VersionCommitDetail);

export type ApiAssignmentsDeleteVersionData = {
    versionId: string;
};

export type ApiAssignmentsDeleteVersionResponse = (Message);

export type ApiAssignmentsRestoreVersionData = {
    id: string;
    versionId: string;
};

export type ApiAssignmentsRestoreVersionResponse = (ApiAssignmentDetail);

export type ApiAssignmentsRevertVersionToDraftData = {
    versionId: string;
};

export type ApiAssignmentsRevertVersionToDraftResponse = (Message);

export type ApiAssignmentsCheckSqlSafetyData = {
    requestBody: {
        [key: string]: unknown;
    };
};

export type ApiAssignmentsCheckSqlSafetyResponse = (unknown);

export type ClientsListClientsData = {
    requestBody: AppClientListIn;
};

export type ClientsListClientsResponse = (AppClientListOut);

export type ClientsCreateClientData = {
    requestBody: AppClientCreate;
};

export type ClientsCreateClientResponse = (AppClientPublic);

export type ClientsUpdateClientData = {
    requestBody: AppClientUpdate;
};

export type ClientsUpdateClientResponse = (AppClientPublic);

export type ClientsDeleteClientData = {
    id: string;
};

export type ClientsDeleteClientResponse = (Message);

export type ClientsRegenerateClientSecretData = {
    id: string;
};

export type ClientsRegenerateClientSecretResponse = (AppClientRegenerateSecretOut);

export type ClientsGetClientData = {
    id: string;
};

export type ClientsGetClientResponse = (AppClientDetail);

export type DatasourcesGetTypesResponse = (Array<(string)>);

export type DatasourcesGetDriversData = {
    type: 'postgres' | 'mysql';
};

export type DatasourcesGetDriversResponse = ({
    [key: string]: Array<(string)>;
});

export type DatasourcesListDatasourcesData = {
    requestBody: DataSourceListIn;
};

export type DatasourcesListDatasourcesResponse = (DataSourceListOut);

export type DatasourcesCreateDatasourceData = {
    requestBody: DataSourceCreate;
};

export type DatasourcesCreateDatasourceResponse = (DataSourcePublic);

export type DatasourcesUpdateDatasourceData = {
    requestBody: DataSourceUpdate;
};

export type DatasourcesUpdateDatasourceResponse = (DataSourcePublic);

export type DatasourcesTestDatasourceData = {
    id: string;
};

export type DatasourcesTestDatasourceResponse = (DataSourceTestResult);

export type DatasourcesGetDatasourceData = {
    id: string;
};

export type DatasourcesGetDatasourceResponse = (DataSourcePublic);

export type DatasourcesDeleteDatasourceData = {
    id: string;
};

export type DatasourcesDeleteDatasourceResponse = (Message);

export type DatasourcesPreTestDatasourceData = {
    requestBody: DataSourcePreTestIn;
};

export type DatasourcesPreTestDatasourceResponse = (DataSourceTestResult);

export type GroupsListGroupsData = {
    requestBody: ApiGroupListIn;
};

export type GroupsListGroupsResponse = (ApiGroupListOut);

export type GroupsCreateGroupData = {
    requestBody: ApiGroupCreate;
};

export type GroupsCreateGroupResponse = (ApiGroupPublic);

export type GroupsUpdateGroupData = {
    requestBody: ApiGroupUpdate;
};

export type GroupsUpdateGroupResponse = (ApiGroupPublic);

export type GroupsDeleteGroupData = {
    id: string;
};

export type GroupsDeleteGroupResponse = (Message);

export type GroupsGetGroupData = {
    id: string;
};

export type GroupsGetGroupResponse = (ApiGroupDetail);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginLogoutResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type MacroDefsListMacroDefsSimpleData = {
    moduleId?: (string | null);
};

export type MacroDefsListMacroDefsSimpleResponse = (Array<ApiMacroDefPublic>);

export type MacroDefsListMacroDefsData = {
    requestBody: ApiMacroDefListIn;
};

export type MacroDefsListMacroDefsResponse = (ApiMacroDefListOut);

export type MacroDefsCreateMacroDefData = {
    requestBody: ApiMacroDefCreate;
};

export type MacroDefsCreateMacroDefResponse = (ApiMacroDefPublic);

export type MacroDefsUpdateMacroDefData = {
    requestBody: ApiMacroDefUpdate;
};

export type MacroDefsUpdateMacroDefResponse = (ApiMacroDefPublic);

export type MacroDefsDeleteMacroDefData = {
    id: string;
};

export type MacroDefsDeleteMacroDefResponse = (Message);

export type MacroDefsGetMacroDefData = {
    id: string;
};

export type MacroDefsGetMacroDefResponse = (ApiMacroDefDetail);

export type MacroDefsPublishMacroDefData = {
    requestBody: ApiMacroDefPublishIn;
};

export type MacroDefsPublishMacroDefResponse = (ApiMacroDefPublic);

export type MacroDefsUnpublishMacroDefData = {
    requestBody: ApiMacroDefPublishIn;
};

export type MacroDefsUnpublishMacroDefResponse = (ApiMacroDefPublic);

export type MacroDefsCreateMacroDefVersionData = {
    id: string;
    requestBody: MacroDefVersionCommitCreate;
};

export type MacroDefsCreateMacroDefVersionResponse = (MacroDefVersionCommitDetail);

export type MacroDefsListMacroDefVersionsData = {
    id: string;
};

export type MacroDefsListMacroDefVersionsResponse = (MacroDefVersionCommitListOut);

export type MacroDefsGetMacroDefVersionData = {
    versionId: string;
};

export type MacroDefsGetMacroDefVersionResponse = (MacroDefVersionCommitDetail);

export type MacroDefsDeleteMacroDefVersionData = {
    versionId: string;
};

export type MacroDefsDeleteMacroDefVersionResponse = (Message);

export type MacroDefsRestoreMacroDefVersionData = {
    id: string;
    versionId: string;
};

export type MacroDefsRestoreMacroDefVersionResponse = (ApiMacroDefPublic);

export type MacroDefsRevertMacroDefVersionToDraftData = {
    versionId: string;
};

export type MacroDefsRevertMacroDefVersionToDraftResponse = (Message);

export type ModulesListModulesSimpleResponse = (Array<ApiModulePublic>);

export type ModulesListModulesData = {
    requestBody: ApiModuleListIn;
};

export type ModulesListModulesResponse = (ApiModuleListOut);

export type ModulesCreateModuleData = {
    requestBody: ApiModuleCreate;
};

export type ModulesCreateModuleResponse = (ApiModulePublic);

export type ModulesUpdateModuleData = {
    requestBody: ApiModuleUpdate;
};

export type ModulesUpdateModuleResponse = (ApiModulePublic);

export type ModulesDeleteModuleData = {
    id: string;
};

export type ModulesDeleteModuleResponse = (Message);

export type ModulesGetModuleData = {
    id: string;
};

export type ModulesGetModuleResponse = (ApiModulePublic);

export type OverviewGetOverviewStatsResponse = (OverviewStats);

export type OverviewGetRequestsByDayData = {
    days?: number;
};

export type OverviewGetRequestsByDayResponse = (RequestsByDayOut);

export type OverviewGetTopPathsData = {
    days?: number;
    limit?: number;
};

export type OverviewGetTopPathsResponse = (TopPathsOut);

export type OverviewGetStatusBreakdownData = {
    days?: number;
};

export type OverviewGetStatusBreakdownResponse = (StatusBreakdownOut);

export type OverviewGetRecentAccessData = {
    limit?: number;
};

export type OverviewGetRecentAccessResponse = (RecentAccessOut);

export type OverviewGetRecentCommitsData = {
    limit?: number;
};

export type OverviewGetRecentCommitsResponse = (RecentCommitsOut);

export type PermissionsGetResourceNamesResponse = (ResourceNamesOut);

export type PermissionsListPermissionsResponse = (PermissionListOut);

export type ReportExecutionsGetExecutionData = {
    execId: string;
};

export type ReportExecutionsGetExecutionResponse = (ReportExecutionPublic);

export type ReportExecutionsDownloadExecutionData = {
    execId: string;
    token?: (string | null);
};

export type ReportExecutionsDownloadExecutionResponse = (unknown);

export type ReportExecutionsListExecutionsData = {
    moduleId?: (string | null);
    page?: number;
    pageSize?: number;
    status?: (ExecutionStatusEnum | null);
    templateId?: (string | null);
};

export type ReportExecutionsListExecutionsResponse = (ReportExecutionListOut);

export type ReportModulesListMinioBucketsData = {
    datasourceId: string;
};

export type ReportModulesListMinioBucketsResponse = (Array<(string)>);

export type ReportModulesListMinioFilesData = {
    bucket: string;
    datasourceId: string;
    prefix?: string;
    suffix?: string;
};

export type ReportModulesListMinioFilesResponse = (Array<(string)>);

export type ReportModulesListExcelSheetsData = {
    bucket: string;
    datasourceId: string;
    filePath: string;
};

export type ReportModulesListExcelSheetsResponse = (Array<(string)>);

export type ReportModulesListModulesData = {
    requestBody: ReportModuleListIn;
};

export type ReportModulesListModulesResponse = (ReportModuleListOut);

export type ReportModulesCreateModuleData = {
    requestBody: ReportModuleCreate;
};

export type ReportModulesCreateModuleResponse = (ReportModuleDetail);

export type ReportModulesUpdateModuleData = {
    requestBody: ReportModuleUpdate;
};

export type ReportModulesUpdateModuleResponse = (ReportModulePublic);

export type ReportModulesDeleteModuleData = {
    id: string;
};

export type ReportModulesDeleteModuleResponse = (Message);

export type ReportModulesGetModuleData = {
    id: string;
};

export type ReportModulesGetModuleResponse = (ReportModuleDetail);

export type ReportModulesGetModuleClientsData = {
    id: string;
};

export type ReportModulesGetModuleClientsResponse = (ClientIdsOut);

export type ReportModulesSetModuleClientsData = {
    id: string;
    requestBody: ClientIdsUpdate;
};

export type ReportModulesSetModuleClientsResponse = (ClientIdsOut);

export type ReportModulesListAllTemplatesData = {
    requestBody: ReportTemplateListIn;
};

export type ReportModulesListAllTemplatesResponse = (ReportTemplateListOut);

export type ReportModulesListTemplatesData = {
    id: string;
    requestBody: ReportTemplateListIn;
};

export type ReportModulesListTemplatesResponse = (ReportTemplateListOut);

export type ReportModulesCreateTemplateData = {
    id: string;
    requestBody: ReportTemplateCreate;
};

export type ReportModulesCreateTemplateResponse = (ReportTemplateDetail);

export type ReportModulesUpdateTemplateData = {
    id: string;
    requestBody: ReportTemplateUpdate;
};

export type ReportModulesUpdateTemplateResponse = (ReportTemplatePublic);

export type ReportModulesDeleteTemplateData = {
    id: string;
    tid: string;
};

export type ReportModulesDeleteTemplateResponse = (Message);

export type ReportModulesGetTemplateData = {
    id: string;
    tid: string;
};

export type ReportModulesGetTemplateResponse = (ReportTemplateDetail);

export type ReportModulesGetTemplateClientsData = {
    id: string;
    tid: string;
};

export type ReportModulesGetTemplateClientsResponse = (ClientIdsOut);

export type ReportModulesSetTemplateClientsData = {
    id: string;
    requestBody: ClientIdsUpdate;
    tid: string;
};

export type ReportModulesSetTemplateClientsResponse = (ClientIdsOut);

export type ReportModulesCreateMappingData = {
    id: string;
    requestBody: SheetMappingCreate;
    tid: string;
};

export type ReportModulesCreateMappingResponse = (SheetMappingPublic);

export type ReportModulesUpdateMappingData = {
    id: string;
    requestBody: SheetMappingUpdate;
    tid: string;
};

export type ReportModulesUpdateMappingResponse = (SheetMappingPublic);

export type ReportModulesBatchUpdateMappingsData = {
    id: string;
    requestBody: SheetMappingBatchUpdate;
    tid: string;
};

export type ReportModulesBatchUpdateMappingsResponse = (Array<SheetMappingPublic>);

export type ReportModulesDeleteMappingData = {
    id: string;
    mappingId: string;
    tid: string;
};

export type ReportModulesDeleteMappingResponse = (Message);

export type ReportModulesGenerateData = {
    id: string;
    requestBody: ReportGenerateIn;
    tid: string;
};

export type ReportModulesGenerateResponse = (ReportGenerateOut);

export type ReportModulesPreviewTemplateData = {
    id: string;
    requestBody: ReportPreviewIn;
    tid: string;
};

export type ReportModulesPreviewTemplateResponse = (ReportPreviewOut);

export type ReportModulesListTemplateExecutionsData = {
    id: string;
    page?: number;
    pageSize?: number;
    tid: string;
};

export type ReportModulesListTemplateExecutionsResponse = (ReportExecutionListOut);

export type ReportModulesClientListModulesData = {
    requestBody: ReportModuleListIn;
};

export type ReportModulesClientListModulesResponse = (ReportModuleListOut);

export type ReportModulesClientListTemplatesData = {
    requestBody: ReportTemplateListIn;
};

export type ReportModulesClientListTemplatesResponse = (ReportTemplateListOut);

export type ReportModulesClientGetTemplateData = {
    tid: string;
};

export type ReportModulesClientGetTemplateResponse = (ReportTemplateDetail);

export type ReportModulesClientGetExecutionData = {
    execId: string;
};

export type ReportModulesClientGetExecutionResponse = (ReportExecutionPublic);

export type ReportModulesClientListExecutionsData = {
    moduleId?: (string | null);
    page?: number;
    pageSize?: number;
    status?: (ExecutionStatusEnum | null);
    templateId?: (string | null);
};

export type ReportModulesClientListExecutionsResponse = (ReportExecutionListOut);

export type ReportModulesClientGetModuleData = {
    mid: string;
};

export type ReportModulesClientGetModuleResponse = (ReportModuleDetail);

export type ReportModulesClientCreateTemplateData = {
    mid: string;
    requestBody: ReportTemplateCreate;
};

export type ReportModulesClientCreateTemplateResponse = (ReportTemplateDetail);

export type ReportModulesClientUpdateTemplateData = {
    mid: string;
    requestBody: ReportTemplateUpdate;
};

export type ReportModulesClientUpdateTemplateResponse = (ReportTemplatePublic);

export type ReportModulesClientDeleteTemplateData = {
    mid: string;
    tid: string;
};

export type ReportModulesClientDeleteTemplateResponse = (Message);

export type ReportModulesClientCreateMappingData = {
    mid: string;
    requestBody: SheetMappingCreate;
    tid: string;
};

export type ReportModulesClientCreateMappingResponse = (SheetMappingPublic);

export type ReportModulesClientUpdateMappingData = {
    mid: string;
    requestBody: SheetMappingUpdate;
    tid: string;
};

export type ReportModulesClientUpdateMappingResponse = (SheetMappingPublic);

export type ReportModulesClientBatchUpdateMappingsData = {
    mid: string;
    requestBody: SheetMappingBatchUpdate;
    tid: string;
};

export type ReportModulesClientBatchUpdateMappingsResponse = (Array<SheetMappingPublic>);

export type ReportModulesClientDeleteMappingData = {
    mappingId: string;
    mid: string;
    tid: string;
};

export type ReportModulesClientDeleteMappingResponse = (Message);

export type ReportModulesClientGetTemplateClientsData = {
    mid: string;
    tid: string;
};

export type ReportModulesClientGetTemplateClientsResponse = (ClientIdsOut);

export type ReportModulesClientSetTemplateClientsData = {
    mid: string;
    requestBody: ClientIdsUpdate;
    tid: string;
};

export type ReportModulesClientSetTemplateClientsResponse = (ClientIdsOut);

export type ReportModulesClientListTemplateExecutionsData = {
    mid: string;
    page?: number;
    pageSize?: number;
    tid: string;
};

export type ReportModulesClientListTemplateExecutionsResponse = (ReportExecutionListOut);

export type ReportModulesClientListBucketsData = {
    datasourceId: string;
};

export type ReportModulesClientListBucketsResponse = (Array<(string)>);

export type ReportModulesClientListFilesData = {
    bucket: string;
    datasourceId: string;
    prefix?: string;
    suffix?: string;
};

export type ReportModulesClientListFilesResponse = (Array<(string)>);

export type ReportModulesClientListSheetsData = {
    bucket: string;
    datasourceId: string;
    filePath: string;
};

export type ReportModulesClientListSheetsResponse = (Array<(string)>);

export type RolesCreateRoleData = {
    requestBody: RoleCreateIn;
};

export type RolesCreateRoleResponse = (RoleDetailOut);

export type RolesListRolesResponse = (RoleListOut);

export type RolesListRoleUsersData = {
    id: string;
};

export type RolesListRoleUsersResponse = (RoleUsersOut);

export type RolesGetRoleData = {
    id: string;
};

export type RolesGetRoleResponse = (RoleDetailOut);

export type RolesUpdateRoleData = {
    id: string;
    requestBody: RoleUpdateIn;
};

export type RolesUpdateRoleResponse = (RoleDetailOut);

export type RolesDeleteRoleData = {
    id: string;
};

export type RolesDeleteRoleResponse = (void);

export type TokenTokenGenerateResponse = (GatewayTokenResponse);

export type TokenTokenGenerateGetData = {
    clientId: string;
    secret: string;
};

export type TokenTokenGenerateGetResponse = (GatewayTokenGenerateGetResponse);

export type TokenTokenGenerate1Response = (GatewayTokenResponse);

export type TokenTokenGenerateGet1Data = {
    clientId: string;
    secret: string;
};

export type TokenTokenGenerateGet1Response = (GatewayTokenGenerateGetResponse);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadMyPermissionsResponse = (MyPermissionsOut);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UsersGetUserRolesData = {
    userId: string;
};

export type UsersGetUserRolesResponse = (UserRolesOut);

export type UsersUpdateUserRolesData = {
    requestBody: UserRolesUpdateIn;
    userId: string;
};

export type UsersUpdateUserRolesResponse = (UserRolesOut);

export type UtilsLivenessResponse = (unknown);

export type UtilsHealthCheckResponse = (unknown);