/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutAboutRouteImport } from './routes/_layout/about'
import { Route as LayoutConnectionIndexRouteImport } from './routes/_layout/connection/index'
import { Route as LayoutApiRepositoryIndexRouteImport } from './routes/_layout/api-repository/index'
import { Route as LayoutApiDevIndexRouteImport } from './routes/_layout/api-dev/index'
import { Route as LayoutSystemClientsRouteImport } from './routes/_layout/system/clients'
import { Route as LayoutConnectionCreateRouteImport } from './routes/_layout/connection/create'
import { Route as LayoutConnectionIdRouteImport } from './routes/_layout/connection/$id'
import { Route as LayoutApiRepositoryIdRouteImport } from './routes/_layout/api-repository/$id'
import { Route as LayoutAboutSqlJinjaRouteImport } from './routes/_layout/about.sql-jinja'
import { Route as LayoutAboutPythonScriptRouteImport } from './routes/_layout/about.python-script'
import { Route as LayoutSystemGroupsIndexRouteImport } from './routes/_layout/system/groups/index'
import { Route as LayoutApiDevModulesIndexRouteImport } from './routes/_layout/api-dev/modules/index'
import { Route as LayoutApiDevMacroDefsIndexRouteImport } from './routes/_layout/api-dev/macro-defs/index'
import { Route as LayoutApiDevApisIndexRouteImport } from './routes/_layout/api-dev/apis/index'
import { Route as LayoutSystemGroupsIdRouteImport } from './routes/_layout/system/groups/$id'
import { Route as LayoutConnectionIdEditRouteImport } from './routes/_layout/connection/$id/edit'
import { Route as LayoutApiDevModulesCreateRouteImport } from './routes/_layout/api-dev/modules/create'
import { Route as LayoutApiDevModulesIdRouteImport } from './routes/_layout/api-dev/modules/$id'
import { Route as LayoutApiDevMacroDefsCreateRouteImport } from './routes/_layout/api-dev/macro-defs/create'
import { Route as LayoutApiDevMacroDefsIdRouteImport } from './routes/_layout/api-dev/macro-defs/$id'
import { Route as LayoutApiDevApisCreateRouteImport } from './routes/_layout/api-dev/apis/create'
import { Route as LayoutApiDevApisIdRouteImport } from './routes/_layout/api-dev/apis/$id'
import { Route as LayoutApiDevModulesIdEditRouteImport } from './routes/_layout/api-dev/modules/$id.edit'
import { Route as LayoutApiDevMacroDefsIdEditRouteImport } from './routes/_layout/api-dev/macro-defs/$id.edit'
import { Route as LayoutApiDevApisIdEditRouteImport } from './routes/_layout/api-dev/apis/$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConnectionIndexRoute = LayoutConnectionIndexRouteImport.update({
  id: '/connection/',
  path: '/connection/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApiRepositoryIndexRoute =
  LayoutApiRepositoryIndexRouteImport.update({
    id: '/api-repository/',
    path: '/api-repository/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutApiDevIndexRoute = LayoutApiDevIndexRouteImport.update({
  id: '/api-dev/',
  path: '/api-dev/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemClientsRoute = LayoutSystemClientsRouteImport.update({
  id: '/system/clients',
  path: '/system/clients',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConnectionCreateRoute = LayoutConnectionCreateRouteImport.update({
  id: '/connection/create',
  path: '/connection/create',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConnectionIdRoute = LayoutConnectionIdRouteImport.update({
  id: '/connection/$id',
  path: '/connection/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApiRepositoryIdRoute = LayoutApiRepositoryIdRouteImport.update({
  id: '/api-repository/$id',
  path: '/api-repository/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutSqlJinjaRoute = LayoutAboutSqlJinjaRouteImport.update({
  id: '/sql-jinja',
  path: '/sql-jinja',
  getParentRoute: () => LayoutAboutRoute,
} as any)
const LayoutAboutPythonScriptRoute = LayoutAboutPythonScriptRouteImport.update({
  id: '/python-script',
  path: '/python-script',
  getParentRoute: () => LayoutAboutRoute,
} as any)
const LayoutSystemGroupsIndexRoute = LayoutSystemGroupsIndexRouteImport.update({
  id: '/system/groups/',
  path: '/system/groups/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApiDevModulesIndexRoute =
  LayoutApiDevModulesIndexRouteImport.update({
    id: '/api-dev/modules/',
    path: '/api-dev/modules/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutApiDevMacroDefsIndexRoute =
  LayoutApiDevMacroDefsIndexRouteImport.update({
    id: '/api-dev/macro-defs/',
    path: '/api-dev/macro-defs/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutApiDevApisIndexRoute = LayoutApiDevApisIndexRouteImport.update({
  id: '/api-dev/apis/',
  path: '/api-dev/apis/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemGroupsIdRoute = LayoutSystemGroupsIdRouteImport.update({
  id: '/system/groups/$id',
  path: '/system/groups/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConnectionIdEditRoute = LayoutConnectionIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => LayoutConnectionIdRoute,
} as any)
const LayoutApiDevModulesCreateRoute =
  LayoutApiDevModulesCreateRouteImport.update({
    id: '/api-dev/modules/create',
    path: '/api-dev/modules/create',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutApiDevModulesIdRoute = LayoutApiDevModulesIdRouteImport.update({
  id: '/api-dev/modules/$id',
  path: '/api-dev/modules/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApiDevMacroDefsCreateRoute =
  LayoutApiDevMacroDefsCreateRouteImport.update({
    id: '/api-dev/macro-defs/create',
    path: '/api-dev/macro-defs/create',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutApiDevMacroDefsIdRoute = LayoutApiDevMacroDefsIdRouteImport.update({
  id: '/api-dev/macro-defs/$id',
  path: '/api-dev/macro-defs/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApiDevApisCreateRoute = LayoutApiDevApisCreateRouteImport.update({
  id: '/api-dev/apis/create',
  path: '/api-dev/apis/create',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApiDevApisIdRoute = LayoutApiDevApisIdRouteImport.update({
  id: '/api-dev/apis/$id',
  path: '/api-dev/apis/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApiDevModulesIdEditRoute =
  LayoutApiDevModulesIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => LayoutApiDevModulesIdRoute,
  } as any)
const LayoutApiDevMacroDefsIdEditRoute =
  LayoutApiDevMacroDefsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => LayoutApiDevMacroDefsIdRoute,
  } as any)
const LayoutApiDevApisIdEditRoute = LayoutApiDevApisIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => LayoutApiDevApisIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/about': typeof LayoutAboutRouteWithChildren
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
  '/about/python-script': typeof LayoutAboutPythonScriptRoute
  '/about/sql-jinja': typeof LayoutAboutSqlJinjaRoute
  '/api-repository/$id': typeof LayoutApiRepositoryIdRoute
  '/connection/$id': typeof LayoutConnectionIdRouteWithChildren
  '/connection/create': typeof LayoutConnectionCreateRoute
  '/system/clients': typeof LayoutSystemClientsRoute
  '/api-dev/': typeof LayoutApiDevIndexRoute
  '/api-repository/': typeof LayoutApiRepositoryIndexRoute
  '/connection/': typeof LayoutConnectionIndexRoute
  '/api-dev/apis/$id': typeof LayoutApiDevApisIdRouteWithChildren
  '/api-dev/apis/create': typeof LayoutApiDevApisCreateRoute
  '/api-dev/macro-defs/$id': typeof LayoutApiDevMacroDefsIdRouteWithChildren
  '/api-dev/macro-defs/create': typeof LayoutApiDevMacroDefsCreateRoute
  '/api-dev/modules/$id': typeof LayoutApiDevModulesIdRouteWithChildren
  '/api-dev/modules/create': typeof LayoutApiDevModulesCreateRoute
  '/connection/$id/edit': typeof LayoutConnectionIdEditRoute
  '/system/groups/$id': typeof LayoutSystemGroupsIdRoute
  '/api-dev/apis/': typeof LayoutApiDevApisIndexRoute
  '/api-dev/macro-defs/': typeof LayoutApiDevMacroDefsIndexRoute
  '/api-dev/modules/': typeof LayoutApiDevModulesIndexRoute
  '/system/groups/': typeof LayoutSystemGroupsIndexRoute
  '/api-dev/apis/$id/edit': typeof LayoutApiDevApisIdEditRoute
  '/api-dev/macro-defs/$id/edit': typeof LayoutApiDevMacroDefsIdEditRoute
  '/api-dev/modules/$id/edit': typeof LayoutApiDevModulesIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/about': typeof LayoutAboutRouteWithChildren
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/about/python-script': typeof LayoutAboutPythonScriptRoute
  '/about/sql-jinja': typeof LayoutAboutSqlJinjaRoute
  '/api-repository/$id': typeof LayoutApiRepositoryIdRoute
  '/connection/$id': typeof LayoutConnectionIdRouteWithChildren
  '/connection/create': typeof LayoutConnectionCreateRoute
  '/system/clients': typeof LayoutSystemClientsRoute
  '/api-dev': typeof LayoutApiDevIndexRoute
  '/api-repository': typeof LayoutApiRepositoryIndexRoute
  '/connection': typeof LayoutConnectionIndexRoute
  '/api-dev/apis/$id': typeof LayoutApiDevApisIdRouteWithChildren
  '/api-dev/apis/create': typeof LayoutApiDevApisCreateRoute
  '/api-dev/macro-defs/$id': typeof LayoutApiDevMacroDefsIdRouteWithChildren
  '/api-dev/macro-defs/create': typeof LayoutApiDevMacroDefsCreateRoute
  '/api-dev/modules/$id': typeof LayoutApiDevModulesIdRouteWithChildren
  '/api-dev/modules/create': typeof LayoutApiDevModulesCreateRoute
  '/connection/$id/edit': typeof LayoutConnectionIdEditRoute
  '/system/groups/$id': typeof LayoutSystemGroupsIdRoute
  '/api-dev/apis': typeof LayoutApiDevApisIndexRoute
  '/api-dev/macro-defs': typeof LayoutApiDevMacroDefsIndexRoute
  '/api-dev/modules': typeof LayoutApiDevModulesIndexRoute
  '/system/groups': typeof LayoutSystemGroupsIndexRoute
  '/api-dev/apis/$id/edit': typeof LayoutApiDevApisIdEditRoute
  '/api-dev/macro-defs/$id/edit': typeof LayoutApiDevMacroDefsIdEditRoute
  '/api-dev/modules/$id/edit': typeof LayoutApiDevModulesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/about': typeof LayoutAboutRouteWithChildren
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/about/python-script': typeof LayoutAboutPythonScriptRoute
  '/_layout/about/sql-jinja': typeof LayoutAboutSqlJinjaRoute
  '/_layout/api-repository/$id': typeof LayoutApiRepositoryIdRoute
  '/_layout/connection/$id': typeof LayoutConnectionIdRouteWithChildren
  '/_layout/connection/create': typeof LayoutConnectionCreateRoute
  '/_layout/system/clients': typeof LayoutSystemClientsRoute
  '/_layout/api-dev/': typeof LayoutApiDevIndexRoute
  '/_layout/api-repository/': typeof LayoutApiRepositoryIndexRoute
  '/_layout/connection/': typeof LayoutConnectionIndexRoute
  '/_layout/api-dev/apis/$id': typeof LayoutApiDevApisIdRouteWithChildren
  '/_layout/api-dev/apis/create': typeof LayoutApiDevApisCreateRoute
  '/_layout/api-dev/macro-defs/$id': typeof LayoutApiDevMacroDefsIdRouteWithChildren
  '/_layout/api-dev/macro-defs/create': typeof LayoutApiDevMacroDefsCreateRoute
  '/_layout/api-dev/modules/$id': typeof LayoutApiDevModulesIdRouteWithChildren
  '/_layout/api-dev/modules/create': typeof LayoutApiDevModulesCreateRoute
  '/_layout/connection/$id/edit': typeof LayoutConnectionIdEditRoute
  '/_layout/system/groups/$id': typeof LayoutSystemGroupsIdRoute
  '/_layout/api-dev/apis/': typeof LayoutApiDevApisIndexRoute
  '/_layout/api-dev/macro-defs/': typeof LayoutApiDevMacroDefsIndexRoute
  '/_layout/api-dev/modules/': typeof LayoutApiDevModulesIndexRoute
  '/_layout/system/groups/': typeof LayoutSystemGroupsIndexRoute
  '/_layout/api-dev/apis/$id/edit': typeof LayoutApiDevApisIdEditRoute
  '/_layout/api-dev/macro-defs/$id/edit': typeof LayoutApiDevMacroDefsIdEditRoute
  '/_layout/api-dev/modules/$id/edit': typeof LayoutApiDevModulesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/about'
    | '/admin'
    | '/settings'
    | '/about/python-script'
    | '/about/sql-jinja'
    | '/api-repository/$id'
    | '/connection/$id'
    | '/connection/create'
    | '/system/clients'
    | '/api-dev/'
    | '/api-repository/'
    | '/connection/'
    | '/api-dev/apis/$id'
    | '/api-dev/apis/create'
    | '/api-dev/macro-defs/$id'
    | '/api-dev/macro-defs/create'
    | '/api-dev/modules/$id'
    | '/api-dev/modules/create'
    | '/connection/$id/edit'
    | '/system/groups/$id'
    | '/api-dev/apis/'
    | '/api-dev/macro-defs/'
    | '/api-dev/modules/'
    | '/system/groups/'
    | '/api-dev/apis/$id/edit'
    | '/api-dev/macro-defs/$id/edit'
    | '/api-dev/modules/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/about'
    | '/admin'
    | '/settings'
    | '/'
    | '/about/python-script'
    | '/about/sql-jinja'
    | '/api-repository/$id'
    | '/connection/$id'
    | '/connection/create'
    | '/system/clients'
    | '/api-dev'
    | '/api-repository'
    | '/connection'
    | '/api-dev/apis/$id'
    | '/api-dev/apis/create'
    | '/api-dev/macro-defs/$id'
    | '/api-dev/macro-defs/create'
    | '/api-dev/modules/$id'
    | '/api-dev/modules/create'
    | '/connection/$id/edit'
    | '/system/groups/$id'
    | '/api-dev/apis'
    | '/api-dev/macro-defs'
    | '/api-dev/modules'
    | '/system/groups'
    | '/api-dev/apis/$id/edit'
    | '/api-dev/macro-defs/$id/edit'
    | '/api-dev/modules/$id/edit'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/about'
    | '/_layout/admin'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/about/python-script'
    | '/_layout/about/sql-jinja'
    | '/_layout/api-repository/$id'
    | '/_layout/connection/$id'
    | '/_layout/connection/create'
    | '/_layout/system/clients'
    | '/_layout/api-dev/'
    | '/_layout/api-repository/'
    | '/_layout/connection/'
    | '/_layout/api-dev/apis/$id'
    | '/_layout/api-dev/apis/create'
    | '/_layout/api-dev/macro-defs/$id'
    | '/_layout/api-dev/macro-defs/create'
    | '/_layout/api-dev/modules/$id'
    | '/_layout/api-dev/modules/create'
    | '/_layout/connection/$id/edit'
    | '/_layout/system/groups/$id'
    | '/_layout/api-dev/apis/'
    | '/_layout/api-dev/macro-defs/'
    | '/_layout/api-dev/modules/'
    | '/_layout/system/groups/'
    | '/_layout/api-dev/apis/$id/edit'
    | '/_layout/api-dev/macro-defs/$id/edit'
    | '/_layout/api-dev/modules/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/connection/': {
      id: '/_layout/connection/'
      path: '/connection'
      fullPath: '/connection/'
      preLoaderRoute: typeof LayoutConnectionIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/api-repository/': {
      id: '/_layout/api-repository/'
      path: '/api-repository'
      fullPath: '/api-repository/'
      preLoaderRoute: typeof LayoutApiRepositoryIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/api-dev/': {
      id: '/_layout/api-dev/'
      path: '/api-dev'
      fullPath: '/api-dev/'
      preLoaderRoute: typeof LayoutApiDevIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/clients': {
      id: '/_layout/system/clients'
      path: '/system/clients'
      fullPath: '/system/clients'
      preLoaderRoute: typeof LayoutSystemClientsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/connection/create': {
      id: '/_layout/connection/create'
      path: '/connection/create'
      fullPath: '/connection/create'
      preLoaderRoute: typeof LayoutConnectionCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/connection/$id': {
      id: '/_layout/connection/$id'
      path: '/connection/$id'
      fullPath: '/connection/$id'
      preLoaderRoute: typeof LayoutConnectionIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/api-repository/$id': {
      id: '/_layout/api-repository/$id'
      path: '/api-repository/$id'
      fullPath: '/api-repository/$id'
      preLoaderRoute: typeof LayoutApiRepositoryIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about/sql-jinja': {
      id: '/_layout/about/sql-jinja'
      path: '/sql-jinja'
      fullPath: '/about/sql-jinja'
      preLoaderRoute: typeof LayoutAboutSqlJinjaRouteImport
      parentRoute: typeof LayoutAboutRoute
    }
    '/_layout/about/python-script': {
      id: '/_layout/about/python-script'
      path: '/python-script'
      fullPath: '/about/python-script'
      preLoaderRoute: typeof LayoutAboutPythonScriptRouteImport
      parentRoute: typeof LayoutAboutRoute
    }
    '/_layout/system/groups/': {
      id: '/_layout/system/groups/'
      path: '/system/groups'
      fullPath: '/system/groups/'
      preLoaderRoute: typeof LayoutSystemGroupsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/api-dev/modules/': {
      id: '/_layout/api-dev/modules/'
      path: '/api-dev/modules'
      fullPath: '/api-dev/modules/'
      preLoaderRoute: typeof LayoutApiDevModulesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/api-dev/macro-defs/': {
      id: '/_layout/api-dev/macro-defs/'
      path: '/api-dev/macro-defs'
      fullPath: '/api-dev/macro-defs/'
      preLoaderRoute: typeof LayoutApiDevMacroDefsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/api-dev/apis/': {
      id: '/_layout/api-dev/apis/'
      path: '/api-dev/apis'
      fullPath: '/api-dev/apis/'
      preLoaderRoute: typeof LayoutApiDevApisIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system/groups/$id': {
      id: '/_layout/system/groups/$id'
      path: '/system/groups/$id'
      fullPath: '/system/groups/$id'
      preLoaderRoute: typeof LayoutSystemGroupsIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/connection/$id/edit': {
      id: '/_layout/connection/$id/edit'
      path: '/edit'
      fullPath: '/connection/$id/edit'
      preLoaderRoute: typeof LayoutConnectionIdEditRouteImport
      parentRoute: typeof LayoutConnectionIdRoute
    }
    '/_layout/api-dev/modules/create': {
      id: '/_layout/api-dev/modules/create'
      path: '/api-dev/modules/create'
      fullPath: '/api-dev/modules/create'
      preLoaderRoute: typeof LayoutApiDevModulesCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/api-dev/modules/$id': {
      id: '/_layout/api-dev/modules/$id'
      path: '/api-dev/modules/$id'
      fullPath: '/api-dev/modules/$id'
      preLoaderRoute: typeof LayoutApiDevModulesIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/api-dev/macro-defs/create': {
      id: '/_layout/api-dev/macro-defs/create'
      path: '/api-dev/macro-defs/create'
      fullPath: '/api-dev/macro-defs/create'
      preLoaderRoute: typeof LayoutApiDevMacroDefsCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/api-dev/macro-defs/$id': {
      id: '/_layout/api-dev/macro-defs/$id'
      path: '/api-dev/macro-defs/$id'
      fullPath: '/api-dev/macro-defs/$id'
      preLoaderRoute: typeof LayoutApiDevMacroDefsIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/api-dev/apis/create': {
      id: '/_layout/api-dev/apis/create'
      path: '/api-dev/apis/create'
      fullPath: '/api-dev/apis/create'
      preLoaderRoute: typeof LayoutApiDevApisCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/api-dev/apis/$id': {
      id: '/_layout/api-dev/apis/$id'
      path: '/api-dev/apis/$id'
      fullPath: '/api-dev/apis/$id'
      preLoaderRoute: typeof LayoutApiDevApisIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/api-dev/modules/$id/edit': {
      id: '/_layout/api-dev/modules/$id/edit'
      path: '/edit'
      fullPath: '/api-dev/modules/$id/edit'
      preLoaderRoute: typeof LayoutApiDevModulesIdEditRouteImport
      parentRoute: typeof LayoutApiDevModulesIdRoute
    }
    '/_layout/api-dev/macro-defs/$id/edit': {
      id: '/_layout/api-dev/macro-defs/$id/edit'
      path: '/edit'
      fullPath: '/api-dev/macro-defs/$id/edit'
      preLoaderRoute: typeof LayoutApiDevMacroDefsIdEditRouteImport
      parentRoute: typeof LayoutApiDevMacroDefsIdRoute
    }
    '/_layout/api-dev/apis/$id/edit': {
      id: '/_layout/api-dev/apis/$id/edit'
      path: '/edit'
      fullPath: '/api-dev/apis/$id/edit'
      preLoaderRoute: typeof LayoutApiDevApisIdEditRouteImport
      parentRoute: typeof LayoutApiDevApisIdRoute
    }
  }
}

interface LayoutAboutRouteChildren {
  LayoutAboutPythonScriptRoute: typeof LayoutAboutPythonScriptRoute
  LayoutAboutSqlJinjaRoute: typeof LayoutAboutSqlJinjaRoute
}

const LayoutAboutRouteChildren: LayoutAboutRouteChildren = {
  LayoutAboutPythonScriptRoute: LayoutAboutPythonScriptRoute,
  LayoutAboutSqlJinjaRoute: LayoutAboutSqlJinjaRoute,
}

const LayoutAboutRouteWithChildren = LayoutAboutRoute._addFileChildren(
  LayoutAboutRouteChildren,
)

interface LayoutConnectionIdRouteChildren {
  LayoutConnectionIdEditRoute: typeof LayoutConnectionIdEditRoute
}

const LayoutConnectionIdRouteChildren: LayoutConnectionIdRouteChildren = {
  LayoutConnectionIdEditRoute: LayoutConnectionIdEditRoute,
}

const LayoutConnectionIdRouteWithChildren =
  LayoutConnectionIdRoute._addFileChildren(LayoutConnectionIdRouteChildren)

interface LayoutApiDevApisIdRouteChildren {
  LayoutApiDevApisIdEditRoute: typeof LayoutApiDevApisIdEditRoute
}

const LayoutApiDevApisIdRouteChildren: LayoutApiDevApisIdRouteChildren = {
  LayoutApiDevApisIdEditRoute: LayoutApiDevApisIdEditRoute,
}

const LayoutApiDevApisIdRouteWithChildren =
  LayoutApiDevApisIdRoute._addFileChildren(LayoutApiDevApisIdRouteChildren)

interface LayoutApiDevMacroDefsIdRouteChildren {
  LayoutApiDevMacroDefsIdEditRoute: typeof LayoutApiDevMacroDefsIdEditRoute
}

const LayoutApiDevMacroDefsIdRouteChildren: LayoutApiDevMacroDefsIdRouteChildren =
  {
    LayoutApiDevMacroDefsIdEditRoute: LayoutApiDevMacroDefsIdEditRoute,
  }

const LayoutApiDevMacroDefsIdRouteWithChildren =
  LayoutApiDevMacroDefsIdRoute._addFileChildren(
    LayoutApiDevMacroDefsIdRouteChildren,
  )

interface LayoutApiDevModulesIdRouteChildren {
  LayoutApiDevModulesIdEditRoute: typeof LayoutApiDevModulesIdEditRoute
}

const LayoutApiDevModulesIdRouteChildren: LayoutApiDevModulesIdRouteChildren = {
  LayoutApiDevModulesIdEditRoute: LayoutApiDevModulesIdEditRoute,
}

const LayoutApiDevModulesIdRouteWithChildren =
  LayoutApiDevModulesIdRoute._addFileChildren(
    LayoutApiDevModulesIdRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRouteWithChildren
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutApiRepositoryIdRoute: typeof LayoutApiRepositoryIdRoute
  LayoutConnectionIdRoute: typeof LayoutConnectionIdRouteWithChildren
  LayoutConnectionCreateRoute: typeof LayoutConnectionCreateRoute
  LayoutSystemClientsRoute: typeof LayoutSystemClientsRoute
  LayoutApiDevIndexRoute: typeof LayoutApiDevIndexRoute
  LayoutApiRepositoryIndexRoute: typeof LayoutApiRepositoryIndexRoute
  LayoutConnectionIndexRoute: typeof LayoutConnectionIndexRoute
  LayoutApiDevApisIdRoute: typeof LayoutApiDevApisIdRouteWithChildren
  LayoutApiDevApisCreateRoute: typeof LayoutApiDevApisCreateRoute
  LayoutApiDevMacroDefsIdRoute: typeof LayoutApiDevMacroDefsIdRouteWithChildren
  LayoutApiDevMacroDefsCreateRoute: typeof LayoutApiDevMacroDefsCreateRoute
  LayoutApiDevModulesIdRoute: typeof LayoutApiDevModulesIdRouteWithChildren
  LayoutApiDevModulesCreateRoute: typeof LayoutApiDevModulesCreateRoute
  LayoutSystemGroupsIdRoute: typeof LayoutSystemGroupsIdRoute
  LayoutApiDevApisIndexRoute: typeof LayoutApiDevApisIndexRoute
  LayoutApiDevMacroDefsIndexRoute: typeof LayoutApiDevMacroDefsIndexRoute
  LayoutApiDevModulesIndexRoute: typeof LayoutApiDevModulesIndexRoute
  LayoutSystemGroupsIndexRoute: typeof LayoutSystemGroupsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRouteWithChildren,
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutApiRepositoryIdRoute: LayoutApiRepositoryIdRoute,
  LayoutConnectionIdRoute: LayoutConnectionIdRouteWithChildren,
  LayoutConnectionCreateRoute: LayoutConnectionCreateRoute,
  LayoutSystemClientsRoute: LayoutSystemClientsRoute,
  LayoutApiDevIndexRoute: LayoutApiDevIndexRoute,
  LayoutApiRepositoryIndexRoute: LayoutApiRepositoryIndexRoute,
  LayoutConnectionIndexRoute: LayoutConnectionIndexRoute,
  LayoutApiDevApisIdRoute: LayoutApiDevApisIdRouteWithChildren,
  LayoutApiDevApisCreateRoute: LayoutApiDevApisCreateRoute,
  LayoutApiDevMacroDefsIdRoute: LayoutApiDevMacroDefsIdRouteWithChildren,
  LayoutApiDevMacroDefsCreateRoute: LayoutApiDevMacroDefsCreateRoute,
  LayoutApiDevModulesIdRoute: LayoutApiDevModulesIdRouteWithChildren,
  LayoutApiDevModulesCreateRoute: LayoutApiDevModulesCreateRoute,
  LayoutSystemGroupsIdRoute: LayoutSystemGroupsIdRoute,
  LayoutApiDevApisIndexRoute: LayoutApiDevApisIndexRoute,
  LayoutApiDevMacroDefsIndexRoute: LayoutApiDevMacroDefsIndexRoute,
  LayoutApiDevModulesIndexRoute: LayoutApiDevModulesIndexRoute,
  LayoutSystemGroupsIndexRoute: LayoutSystemGroupsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
